const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const scoreEl = document.querySelector('#score'), sectorEl = document.querySelector('#sector'), hullEl = document.querySelector('#hull');
const startScreen = document.querySelector('#startScreen'), startButton = document.querySelector('#startButton'), flash = document.querySelector('#flash');
let w, h, playing = false, paused = false, score = 0, hull = 3, last = 0, spawn = 0, fire = 0, sector = 1;
const keys = {}, stars = [], rocks = [], shots = [], particles = [];
const player = { x: .5, target: .5 };
function resize() { const dpr = devicePixelRatio || 1; w = canvas.clientWidth; h = canvas.clientHeight; canvas.width = w * dpr; canvas.height = h * dpr; ctx.setTransform(dpr,0,0,dpr,0,0); }
addEventListener('resize', resize); resize();
for (let i=0;i<180;i++) stars.push({ x:Math.random(), y:Math.random(), z:Math.random(), hue: 185 + Math.random()*85 });
function project(o) { const z = Math.max(.02, o.z); return { x:w/2+(o.x-.5)*w/z, y:h*.47+(o.y-.5)*h/z, s:1/z }; }
function rock() { rocks.push({x:.12+Math.random()*.76,y:.15+Math.random()*.54,z:1.35,r:.025+Math.random()*.035,rot:Math.random()*6,spin:(Math.random()-.5)*3,hue:Math.random()>.75?290:198}); }
function burst(x,y,color,n=15) { for(let i=0;i<n;i++) particles.push({x,y,dx:(Math.random()-.5)*260,dy:(Math.random()-.5)*260,life:.4+Math.random()*.45,color}); }
function drawRock(r) { const p=project(r), rad=r.r*p.s*w; ctx.save(); ctx.translate(p.x,p.y); ctx.rotate(r.rot); ctx.strokeStyle=`hsla(${r.hue},100%,72%,${Math.min(1,p.s*.22)})`; ctx.lineWidth=Math.max(1,p.s*.45); ctx.shadowBlur=12; ctx.shadowColor=ctx.strokeStyle; ctx.beginPath(); for(let i=0;i<7;i++){let a=i*Math.PI*2/7, q=rad*(.76+(i%3)*.13); i?ctx.lineTo(Math.cos(a)*q,Math.sin(a)*q):ctx.moveTo(Math.cos(a)*q,Math.sin(a)*q)}ctx.closePath();ctx.stroke(); ctx.restore(); }
function drawShip() { const x=player.x*w, y=h*.82; ctx.save();ctx.translate(x,y); ctx.shadowBlur=24;ctx.shadowColor='#56e7ff';ctx.fillStyle='#a4f6ff';ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(17,18);ctx.lineTo(0,12);ctx.lineTo(-17,18);ctx.closePath();ctx.fill();ctx.fillStyle='#855dff';ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(5,10);ctx.lineTo(-5,10);ctx.fill();ctx.fillStyle='rgba(78,224,255,.8)';ctx.beginPath();ctx.moveTo(-10,15);ctx.lineTo(0,37+Math.random()*7);ctx.lineTo(10,15);ctx.fill();ctx.restore(); }
function render(t) { requestAnimationFrame(render); const dt=Math.min(.04,(t-last)/1000||0);last=t; ctx.fillStyle='#050816';ctx.fillRect(0,0,w,h); const g=ctx.createRadialGradient(w/2,h*.42,0,w/2,h*.42,w*.65);g.addColorStop(0,'#19255d');g.addColorStop(.45,'#0a1130');g.addColorStop(1,'#03050e');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 stars.forEach(s=>{s.z-=dt*(playing?(.2+sector*.025):.045);if(s.z<.02){s.z=1;s.x=Math.random();s.y=Math.random()}const p=project(s);ctx.fillStyle=`hsla(${s.hue},100%,75%,${Math.min(1,p.s*.045)})`;ctx.fillRect(p.x,p.y,Math.max(1,p.s*.7),Math.max(1,p.s*2.5));});
 if(!playing||paused) return; player.x += (player.target-player.x)*Math.min(1,dt*9); spawn+=dt; if(spawn>Math.max(.22,.72-sector*.025)){rock();spawn=0} fire-=dt;
 if((keys.Space||keys.click)&&fire<=0){shots.push({x:player.x,y:.78,z:.11});fire=.17;} rocks.forEach(r=>{r.z-=dt*(.17+sector*.012);r.rot+=r.spin*dt}); shots.forEach(s=>s.z+=dt*.9);
 for(let i=rocks.length-1;i>=0;i--){let r=rocks[i], p=project(r); if(r.z<.105 && Math.abs(p.x-player.x*w)<40 && Math.abs(p.y-h*.82)<43){rocks.splice(i,1);hull--;burst(player.x*w,h*.82,'#ff5ca8',28);flash.style.opacity=.35;setTimeout(()=>flash.style.opacity=0,100);hullEl.textContent='● '.repeat(hull)+'○ '.repeat(3-hull);if(!hull) end();continue} let hit=shots.findIndex(s=>Math.abs(s.x-r.x)<r.r*2.4 && Math.abs(s.y-r.y)<r.r*2.4 && Math.abs(s.z-r.z)<.12);if(hit>=0){shots.splice(hit,1);rocks.splice(i,1);score+=100;burst(p.x,p.y,'#7ceeff');continue} if(r.z<.025) rocks.splice(i,1);}
 shots.forEach(s=>{let p=project(s);ctx.strokeStyle='#9affff';ctx.lineWidth=2;ctx.shadowBlur=12;ctx.shadowColor='#63eaff';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x,p.y+18*p.s);ctx.stroke();}); rocks.forEach(drawRock); particles.forEach((p,i)=>{p.life-=dt;p.x+=p.dx*dt;p.y+=p.dy*dt;ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.life*1.5);ctx.fillRect(p.x,p.y,2,2);ctx.globalAlpha=1;if(p.life<=0)particles.splice(i,1)});drawShip();score+=dt*9;sector=1+Math.floor(score/1000);scoreEl.textContent=String(Math.floor(score)).padStart(6,'0');sectorEl.textContent=String(sector).padStart(2,'0'); }
function start(){playing=true;paused=false;score=0;hull=3;rocks.length=shots.length=particles.length=0;hullEl.textContent='● ● ●';startScreen.classList.add('hidden');}
function end(){playing=false;startScreen.querySelector('.eyebrow').textContent='RUN TERMINATED // SCORE '+Math.floor(score);startScreen.querySelector('h1').innerHTML='RIFT<br><em>COLLAPSED</em>';startButton.innerHTML='RUN AGAIN <span>↗</span>';startScreen.classList.remove('hidden');}
startButton.onclick=start; addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyP'&&playing)paused=!paused;if(['Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys[e.code]=false); canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();player.target=(e.clientX-r.left)/r.width});canvas.addEventListener('pointerdown',()=>keys.click=true);addEventListener('pointerup',()=>keys.click=false);setInterval(()=>{if(keys.KeyA||keys.ArrowLeft)player.target=Math.max(.1,player.target-.055);if(keys.KeyD||keys.ArrowRight)player.target=Math.min(.9,player.target+.055)},35); requestAnimationFrame(render);
